spring.datasource.url=jdbc:mysql://localhost:3306/assetvault
spring.datasource.username=root
spring.datasource.password=Vyshu@1808

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080